on:
  schedule:
    - cron: 0 0 * * 5
name: Update
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: package-update
        uses: taichi/actions-package-update@master
        env:
          AUTHOR_EMAIL: john@example.com
          AUTHOR_NAME: github-actions
          EXECUTE: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATE_COMMAND: npm
        with:
          args: update
